language: node_js
sudo: false
node_js:
- 6
services:
- mongodb
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3f91eae9a3ab_key -iv $encrypted_3f91eae9a3ab_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- chmod 600 .travis/id_rsa
- git config --global user.name "alexzhu"
- git config --global user.email zrl920825@hotmail.com
- cp .travis/id_rsa ~/.ssh/travis_deploy
- cp .travis/ssh_config ~/.ssh/config
install:
- npm install pm2 -g
- npm install
script:
after_success:
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/travis_deploy
- git remote add deploy root@202.5.19.112:/root/project/novel.git
- git push deploy
